---
version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data
    volumes:
      - dbdata:/data
    ports:
      - 5432:5432

volumes:
  dbdata: {}